version: '3'

services:
  appsiteimagenasa:
    image: siteimagemnasa
    build:
      context: .
    ports:
      - "20000:80"
    networks:
      - nasa-network
    depends_on:
      - "redisimagemnasa"

  redisimagemnasa:
    image: redis:alpine
    ports:
      - "56379:6379"
    networks:
      - nasa-network

networks: 
    nasa-network:
      driver: bridge